"use client";
import { useState, type FormEvent } from "react";
import type { NewPatientInput } from "@/lib/patientTypes";
interface Props { isOpen:boolean; onClose:()=>void; onAdd:(patient:NewPatientInput)=>Promise<string|null> }
export default function AddPatientModal({isOpen,onClose,onAdd}:Props){
  const [status,setStatus]=useState("معاینه اولیه"); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  if(!isOpen)return null;
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);setSaving(true);const result=await onAdd({fullName:String(data.get("fullName")),nationalId:String(data.get("nationalId")),fileNumber:String(data.get("fileNumber")),age:Number(data.get("age")),phone:String(data.get("phone")),status,medicalHistory:String(data.get("medicalHistory")),username:String(data.get("username")).trim()||undefined,patientPassword:String(data.get("patientPassword"))||undefined});setSaving(false);if(result)return setError(result);onClose()};
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-black">افزودن بیمار جدید</h2><p className="mt-1 text-sm text-slate-500">اطلاعات پرونده بیمار را ثبت کنید.</p></div><button type="button" onClick={onClose} className="grid size-10 place-items-center rounded-xl bg-slate-100 text-xl">×</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><input name="fullName" required placeholder="نام و نام خانوادگی" className="field sm:col-span-2"/><input name="nationalId" required dir="ltr" placeholder="کد ملی" className="field"/><input name="fileNumber" required dir="ltr" placeholder="شماره پرونده" className="field"/><input name="age" required type="number" min={1} max={120} placeholder="سن" className="field"/><input name="phone" required dir="ltr" placeholder="شماره تماس" className="field"/><select value={status} onChange={e=>setStatus(e.target.value)} className="field sm:col-span-2"><option>معاینه اولیه</option><option>تحت درمان</option><option>نیازمند پیگیری</option><option>درمان تکمیل‌شده</option></select><textarea name="medicalHistory" rows={4} placeholder="شرح کوتاه وضعیت یا سابقه درمان" className="field resize-none sm:col-span-2"/><p className="text-xs text-slate-500 sm:col-span-2">برای فعال‌کردن پنل بیمار، دو فیلد زیر را با هم وارد کنید.</p><input name="username" dir="ltr" placeholder="نام کاربری بیمار (اختیاری)" className="field"/><input name="patientPassword" type="password" minLength={8} placeholder="رمز بیمار (حداقل ۸ نویسه)" className="field"/></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex gap-3"><button disabled={saving} className="flex-1 rounded-2xl bg-sky-500 px-5 py-3.5 font-black text-white disabled:opacity-60">{saving?"در حال ثبت...":"ثبت بیمار"}</button><button type="button" onClick={onClose} className="rounded-2xl border border-slate-200 px-5 py-3.5">انصراف</button></div></form></div>
}
